// Liste des pays avec indicatif téléphonique international, générée depuis
// le dataset 'world-countries' (ISO 3166-1 + ITU E.164 calling codes).
// Utilisé par <PhoneInput /> pour le sélecteur d'indicatif (drapeau + code).
export interface CountryDialCode {
  iso2: string;
  name: string;
  dial: string;
  flag: string;
}

export const COUNTRIES: CountryDialCode[] = [
  { iso2: 'AF', name: 'Afghanistan', dial: '93', flag: '🇦🇫' },
  { iso2: 'ZA', name: 'Afrique du Sud', dial: '27', flag: '🇿🇦' },
  { iso2: 'AL', name: 'Albanie', dial: '355', flag: '🇦🇱' },
  { iso2: 'DZ', name: 'Algérie', dial: '213', flag: '🇩🇿' },
  { iso2: 'DE', name: 'Allemagne', dial: '49', flag: '🇩🇪' },
  { iso2: 'AD', name: 'Andorre', dial: '376', flag: '🇦🇩' },
  { iso2: 'AO', name: 'Angola', dial: '244', flag: '🇦🇴' },
  { iso2: 'AG', name: 'Antigua-et-Barbuda', dial: '1268', flag: '🇦🇬' },
  { iso2: 'SA', name: 'Arabie Saoudite', dial: '966', flag: '🇸🇦' },
  { iso2: 'AR', name: 'Argentine', dial: '54', flag: '🇦🇷' },
  { iso2: 'AM', name: 'Arménie', dial: '374', flag: '🇦🇲' },
  { iso2: 'AU', name: 'Australie', dial: '61', flag: '🇦🇺' },
  { iso2: 'AT', name: 'Autriche', dial: '43', flag: '🇦🇹' },
  { iso2: 'AZ', name: 'Azerbaïdjan', dial: '994', flag: '🇦🇿' },
  { iso2: 'BS', name: 'Bahamas', dial: '1242', flag: '🇧🇸' },
  { iso2: 'BH', name: 'Bahreïn', dial: '973', flag: '🇧🇭' },
  { iso2: 'BD', name: 'Bangladesh', dial: '880', flag: '🇧🇩' },
  { iso2: 'BB', name: 'Barbade', dial: '1246', flag: '🇧🇧' },
  { iso2: 'BE', name: 'Belgique', dial: '32', flag: '🇧🇪' },
  { iso2: 'BZ', name: 'Belize', dial: '501', flag: '🇧🇿' },
  { iso2: 'BJ', name: 'Bénin', dial: '229', flag: '🇧🇯' },
  { iso2: 'BT', name: 'Bhoutan', dial: '975', flag: '🇧🇹' },
  { iso2: 'BY', name: 'Biélorussie', dial: '375', flag: '🇧🇾' },
  { iso2: 'MM', name: 'Birmanie', dial: '95', flag: '🇲🇲' },
  { iso2: 'BO', name: 'Bolivie', dial: '591', flag: '🇧🇴' },
  { iso2: 'BA', name: 'Bosnie-Herzégovine', dial: '387', flag: '🇧🇦' },
  { iso2: 'BW', name: 'Botswana', dial: '267', flag: '🇧🇼' },
  { iso2: 'BR', name: 'Brésil', dial: '55', flag: '🇧🇷' },
  { iso2: 'BN', name: 'Brunei', dial: '673', flag: '🇧🇳' },
  { iso2: 'BG', name: 'Bulgarie', dial: '359', flag: '🇧🇬' },
  { iso2: 'BF', name: 'Burkina Faso', dial: '226', flag: '🇧🇫' },
  { iso2: 'BI', name: 'Burundi', dial: '257', flag: '🇧🇮' },
  { iso2: 'KH', name: 'Cambodge', dial: '855', flag: '🇰🇭' },
  { iso2: 'CM', name: 'Cameroun', dial: '237', flag: '🇨🇲' },
  { iso2: 'CA', name: 'Canada', dial: '1', flag: '🇨🇦' },
  { iso2: 'CL', name: 'Chili', dial: '56', flag: '🇨🇱' },
  { iso2: 'CN', name: 'Chine', dial: '86', flag: '🇨🇳' },
  { iso2: 'CY', name: 'Chypre', dial: '357', flag: '🇨🇾' },
  { iso2: 'VA', name: 'Cité du Vatican', dial: '3', flag: '🇻🇦' },
  { iso2: 'CO', name: 'Colombie', dial: '57', flag: '🇨🇴' },
  { iso2: 'KM', name: 'Comores', dial: '269', flag: '🇰🇲' },
  { iso2: 'CG', name: 'Congo', dial: '242', flag: '🇨🇬' },
  { iso2: 'CD', name: 'Congo (Rép. dém.)', dial: '243', flag: '🇨🇩' },
  { iso2: 'KP', name: 'Corée du Nord', dial: '850', flag: '🇰🇵' },
  { iso2: 'KR', name: 'Corée du Sud', dial: '82', flag: '🇰🇷' },
  { iso2: 'CR', name: 'Costa Rica', dial: '506', flag: '🇨🇷' },
  { iso2: 'CI', name: "Côte d'Ivoire", dial: '225', flag: '🇨🇮' },
  { iso2: 'HR', name: 'Croatie', dial: '385', flag: '🇭🇷' },
  { iso2: 'CU', name: 'Cuba', dial: '53', flag: '🇨🇺' },
  { iso2: 'DK', name: 'Danemark', dial: '45', flag: '🇩🇰' },
  { iso2: 'DJ', name: 'Djibouti', dial: '253', flag: '🇩🇯' },
  { iso2: 'DM', name: 'Dominique', dial: '1767', flag: '🇩🇲' },
  { iso2: 'EG', name: 'Égypte', dial: '20', flag: '🇪🇬' },
  { iso2: 'AE', name: 'Émirats arabes unis', dial: '971', flag: '🇦🇪' },
  { iso2: 'EC', name: 'Équateur', dial: '593', flag: '🇪🇨' },
  { iso2: 'ER', name: 'Érythrée', dial: '291', flag: '🇪🇷' },
  { iso2: 'ES', name: 'Espagne', dial: '34', flag: '🇪🇸' },
  { iso2: 'EE', name: 'Estonie', dial: '372', flag: '🇪🇪' },
  { iso2: 'US', name: 'États-Unis', dial: '1', flag: '🇺🇸' },
  { iso2: 'ET', name: 'Éthiopie', dial: '251', flag: '🇪🇹' },
  { iso2: 'FJ', name: 'Fidji', dial: '679', flag: '🇫🇯' },
  { iso2: 'FI', name: 'Finlande', dial: '358', flag: '🇫🇮' },
  { iso2: 'FR', name: 'France', dial: '33', flag: '🇫🇷' },
  { iso2: 'GA', name: 'Gabon', dial: '241', flag: '🇬🇦' },
  { iso2: 'GM', name: 'Gambie', dial: '220', flag: '🇬🇲' },
  { iso2: 'GE', name: 'Géorgie', dial: '995', flag: '🇬🇪' },
  { iso2: 'GH', name: 'Ghana', dial: '233', flag: '🇬🇭' },
  { iso2: 'GR', name: 'Grèce', dial: '30', flag: '🇬🇷' },
  { iso2: 'GD', name: 'Grenade', dial: '1473', flag: '🇬🇩' },
  { iso2: 'GT', name: 'Guatemala', dial: '502', flag: '🇬🇹' },
  { iso2: 'GN', name: 'Guinée', dial: '224', flag: '🇬🇳' },
  { iso2: 'GQ', name: 'Guinée équatoriale', dial: '240', flag: '🇬🇶' },
  { iso2: 'GW', name: 'Guinée-Bissau', dial: '245', flag: '🇬🇼' },
  { iso2: 'GY', name: 'Guyana', dial: '592', flag: '🇬🇾' },
  { iso2: 'HT', name: 'Haïti', dial: '509', flag: '🇭🇹' },
  { iso2: 'HN', name: 'Honduras', dial: '504', flag: '🇭🇳' },
  { iso2: 'HK', name: 'Hong Kong', dial: '852', flag: '🇭🇰' },
  { iso2: 'HU', name: 'Hongrie', dial: '36', flag: '🇭🇺' },
  { iso2: 'MU', name: 'Île Maurice', dial: '230', flag: '🇲🇺' },
  { iso2: 'CV', name: 'Îles du Cap-Vert', dial: '238', flag: '🇨🇻' },
  { iso2: 'MH', name: 'Îles Marshall', dial: '692', flag: '🇲🇭' },
  { iso2: 'SB', name: 'Îles Salomon', dial: '677', flag: '🇸🇧' },
  { iso2: 'IN', name: 'Inde', dial: '91', flag: '🇮🇳' },
  { iso2: 'ID', name: 'Indonésie', dial: '62', flag: '🇮🇩' },
  { iso2: 'IQ', name: 'Irak', dial: '964', flag: '🇮🇶' },
  { iso2: 'IR', name: 'Iran', dial: '98', flag: '🇮🇷' },
  { iso2: 'IE', name: 'Irlande', dial: '353', flag: '🇮🇪' },
  { iso2: 'IS', name: 'Islande', dial: '354', flag: '🇮🇸' },
  { iso2: 'IL', name: 'Israël', dial: '972', flag: '🇮🇱' },
  { iso2: 'IT', name: 'Italie', dial: '39', flag: '🇮🇹' },
  { iso2: 'JM', name: 'Jamaïque', dial: '1876', flag: '🇯🇲' },
  { iso2: 'JP', name: 'Japon', dial: '81', flag: '🇯🇵' },
  { iso2: 'JO', name: 'Jordanie', dial: '962', flag: '🇯🇴' },
  { iso2: 'KZ', name: 'Kazakhstan', dial: '7', flag: '🇰🇿' },
  { iso2: 'KE', name: 'Kenya', dial: '254', flag: '🇰🇪' },
  { iso2: 'KG', name: 'Kirghizistan', dial: '996', flag: '🇰🇬' },
  { iso2: 'KI', name: 'Kiribati', dial: '686', flag: '🇰🇮' },
  { iso2: 'KW', name: 'Koweït', dial: '965', flag: '🇰🇼' },
  { iso2: 'LA', name: 'Laos', dial: '856', flag: '🇱🇦' },
  { iso2: 'LS', name: 'Lesotho', dial: '266', flag: '🇱🇸' },
  { iso2: 'LV', name: 'Lettonie', dial: '371', flag: '🇱🇻' },
  { iso2: 'LB', name: 'Liban', dial: '961', flag: '🇱🇧' },
  { iso2: 'LR', name: 'Liberia', dial: '231', flag: '🇱🇷' },
  { iso2: 'LY', name: 'Libye', dial: '218', flag: '🇱🇾' },
  { iso2: 'LI', name: 'Liechtenstein', dial: '423', flag: '🇱🇮' },
  { iso2: 'LT', name: 'Lituanie', dial: '370', flag: '🇱🇹' },
  { iso2: 'LU', name: 'Luxembourg', dial: '352', flag: '🇱🇺' },
  { iso2: 'MO', name: 'Macao', dial: '853', flag: '🇲🇴' },
  { iso2: 'MK', name: 'Macédoine du Nord', dial: '389', flag: '🇲🇰' },
  { iso2: 'MG', name: 'Madagascar', dial: '261', flag: '🇲🇬' },
  { iso2: 'MY', name: 'Malaisie', dial: '60', flag: '🇲🇾' },
  { iso2: 'MW', name: 'Malawi', dial: '265', flag: '🇲🇼' },
  { iso2: 'MV', name: 'Maldives', dial: '960', flag: '🇲🇻' },
  { iso2: 'ML', name: 'Mali', dial: '223', flag: '🇲🇱' },
  { iso2: 'MT', name: 'Malte', dial: '356', flag: '🇲🇹' },
  { iso2: 'MA', name: 'Maroc', dial: '212', flag: '🇲🇦' },
  { iso2: 'MR', name: 'Mauritanie', dial: '222', flag: '🇲🇷' },
  { iso2: 'MX', name: 'Mexique', dial: '52', flag: '🇲🇽' },
  { iso2: 'FM', name: 'Micronésie', dial: '691', flag: '🇫🇲' },
  { iso2: 'MD', name: 'Moldavie', dial: '373', flag: '🇲🇩' },
  { iso2: 'MC', name: 'Monaco', dial: '377', flag: '🇲🇨' },
  { iso2: 'MN', name: 'Mongolie', dial: '976', flag: '🇲🇳' },
  { iso2: 'ME', name: 'Monténégro', dial: '382', flag: '🇲🇪' },
  { iso2: 'MZ', name: 'Mozambique', dial: '258', flag: '🇲🇿' },
  { iso2: 'NA', name: 'Namibie', dial: '264', flag: '🇳🇦' },
  { iso2: 'NR', name: 'Nauru', dial: '674', flag: '🇳🇷' },
  { iso2: 'NP', name: 'Népal', dial: '977', flag: '🇳🇵' },
  { iso2: 'NI', name: 'Nicaragua', dial: '505', flag: '🇳🇮' },
  { iso2: 'NE', name: 'Niger', dial: '227', flag: '🇳🇪' },
  { iso2: 'NG', name: 'Nigéria', dial: '234', flag: '🇳🇬' },
  { iso2: 'NO', name: 'Norvège', dial: '47', flag: '🇳🇴' },
  { iso2: 'NZ', name: 'Nouvelle-Zélande', dial: '64', flag: '🇳🇿' },
  { iso2: 'OM', name: 'Oman', dial: '968', flag: '🇴🇲' },
  { iso2: 'UG', name: 'Ouganda', dial: '256', flag: '🇺🇬' },
  { iso2: 'UZ', name: 'Ouzbékistan', dial: '998', flag: '🇺🇿' },
  { iso2: 'PK', name: 'Pakistan', dial: '92', flag: '🇵🇰' },
  { iso2: 'PW', name: 'Palaos (Palau)', dial: '680', flag: '🇵🇼' },
  { iso2: 'PS', name: 'Palestine', dial: '970', flag: '🇵🇸' },
  { iso2: 'PA', name: 'Panama', dial: '507', flag: '🇵🇦' },
  { iso2: 'PG', name: 'Papouasie-Nouvelle-Guinée', dial: '675', flag: '🇵🇬' },
  { iso2: 'PY', name: 'Paraguay', dial: '595', flag: '🇵🇾' },
  { iso2: 'NL', name: 'Pays-Bas', dial: '31', flag: '🇳🇱' },
  { iso2: 'PE', name: 'Pérou', dial: '51', flag: '🇵🇪' },
  { iso2: 'PH', name: 'Philippines', dial: '63', flag: '🇵🇭' },
  { iso2: 'PL', name: 'Pologne', dial: '48', flag: '🇵🇱' },
  { iso2: 'PT', name: 'Portugal', dial: '351', flag: '🇵🇹' },
  { iso2: 'QA', name: 'Qatar', dial: '974', flag: '🇶🇦' },
  { iso2: 'CF', name: 'République centrafricaine', dial: '236', flag: '🇨🇫' },
  { iso2: 'DO', name: 'République dominicaine', dial: '1', flag: '🇩🇴' },
  { iso2: 'RO', name: 'Roumanie', dial: '40', flag: '🇷🇴' },
  { iso2: 'GB', name: 'Royaume-Uni', dial: '44', flag: '🇬🇧' },
  { iso2: 'RU', name: 'Russie', dial: '7', flag: '🇷🇺' },
  { iso2: 'RW', name: 'Rwanda', dial: '250', flag: '🇷🇼' },
  { iso2: 'KN', name: 'Saint-Christophe-et-Niévès', dial: '1869', flag: '🇰🇳' },
  { iso2: 'SM', name: 'Saint-Marin', dial: '378', flag: '🇸🇲' },
  { iso2: 'VC', name: 'Saint-Vincent-et-les-Grenadines', dial: '1784', flag: '🇻🇨' },
  { iso2: 'LC', name: 'Sainte-Lucie', dial: '1758', flag: '🇱🇨' },
  { iso2: 'SV', name: 'Salvador', dial: '503', flag: '🇸🇻' },
  { iso2: 'WS', name: 'Samoa', dial: '685', flag: '🇼🇸' },
  { iso2: 'ST', name: 'São Tomé et Príncipe', dial: '239', flag: '🇸🇹' },
  { iso2: 'SN', name: 'Sénégal', dial: '221', flag: '🇸🇳' },
  { iso2: 'RS', name: 'Serbie', dial: '381', flag: '🇷🇸' },
  { iso2: 'SC', name: 'Seychelles', dial: '248', flag: '🇸🇨' },
  { iso2: 'SL', name: 'Sierra Leone', dial: '232', flag: '🇸🇱' },
  { iso2: 'SG', name: 'Singapour', dial: '65', flag: '🇸🇬' },
  { iso2: 'SK', name: 'Slovaquie', dial: '421', flag: '🇸🇰' },
  { iso2: 'SI', name: 'Slovénie', dial: '386', flag: '🇸🇮' },
  { iso2: 'SO', name: 'Somalie', dial: '252', flag: '🇸🇴' },
  { iso2: 'SD', name: 'Soudan', dial: '249', flag: '🇸🇩' },
  { iso2: 'SS', name: 'Soudan du Sud', dial: '211', flag: '🇸🇸' },
  { iso2: 'LK', name: 'Sri Lanka', dial: '94', flag: '🇱🇰' },
  { iso2: 'SE', name: 'Suède', dial: '46', flag: '🇸🇪' },
  { iso2: 'CH', name: 'Suisse', dial: '41', flag: '🇨🇭' },
  { iso2: 'SR', name: 'Surinam', dial: '597', flag: '🇸🇷' },
  { iso2: 'SZ', name: 'Swaziland', dial: '268', flag: '🇸🇿' },
  { iso2: 'SY', name: 'Syrie', dial: '963', flag: '🇸🇾' },
  { iso2: 'TJ', name: 'Tadjikistan', dial: '992', flag: '🇹🇯' },
  { iso2: 'TW', name: 'Taïwan', dial: '886', flag: '🇹🇼' },
  { iso2: 'TZ', name: 'Tanzanie', dial: '255', flag: '🇹🇿' },
  { iso2: 'TD', name: 'Tchad', dial: '235', flag: '🇹🇩' },
  { iso2: 'CZ', name: 'Tchéquie', dial: '420', flag: '🇨🇿' },
  { iso2: 'TH', name: 'Thaïlande', dial: '66', flag: '🇹🇭' },
  { iso2: 'TL', name: 'Timor oriental', dial: '670', flag: '🇹🇱' },
  { iso2: 'TG', name: 'Togo', dial: '228', flag: '🇹🇬' },
  { iso2: 'TO', name: 'Tonga', dial: '676', flag: '🇹🇴' },
  { iso2: 'TT', name: 'Trinité-et-Tobago', dial: '1868', flag: '🇹🇹' },
  { iso2: 'TN', name: 'Tunisie', dial: '216', flag: '🇹🇳' },
  { iso2: 'TM', name: 'Turkménistan', dial: '993', flag: '🇹🇲' },
  { iso2: 'TR', name: 'Turquie', dial: '90', flag: '🇹🇷' },
  { iso2: 'TV', name: 'Tuvalu', dial: '688', flag: '🇹🇻' },
  { iso2: 'UA', name: 'Ukraine', dial: '380', flag: '🇺🇦' },
  { iso2: 'UY', name: 'Uruguay', dial: '598', flag: '🇺🇾' },
  { iso2: 'VU', name: 'Vanuatu', dial: '678', flag: '🇻🇺' },
  { iso2: 'VE', name: 'Venezuela', dial: '58', flag: '🇻🇪' },
  { iso2: 'VN', name: 'Viêt Nam', dial: '84', flag: '🇻🇳' },
  { iso2: 'YE', name: 'Yémen', dial: '967', flag: '🇾🇪' },
  { iso2: 'ZM', name: 'Zambie', dial: '260', flag: '🇿🇲' },
  { iso2: 'ZW', name: 'Zimbabwe', dial: '263', flag: '🇿🇼' },
];

// Sénégal en tête de liste (marché principal), reste trié alphabétiquement.
export const DEFAULT_COUNTRY_ISO2 = 'SN';
