export interface MockListing {
  id: string;
  title: string;
  address: string;
  city: string;
  region: string;
  price: number;
  type: string;
  surface: number;
  rooms: number;
  beds: number;
  baths: number;
  isNew: boolean;
  isVerified: boolean;
  boostUntil?: string;
  description: string;
  amenities: string[];
  images: string[];
  createdAt: string;
  landlordName: string;
  landlordEmail: string;
}

export const MOCK_LISTINGS: MockListing[] = [
  /* ── DAKAR ─────────────────────────────────────────────── */
  {
    id: '1',
    title: 'Appartement 3 Pièces Meublé',
    address: 'Rue du Plateau',
    city: 'Plateau, Dakar',
    region: 'Dakar',
    price: 350000,
    type: 'APPARTEMENT',
    surface: 85,
    rooms: 3, beds: 2, baths: 1,
    isNew: true, isVerified: true,
    boostUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Bel appartement meublé de 3 pièces situé au cœur du Plateau, quartier d\'affaires et résidentiel prisé de Dakar. Lumineux, calme et bien entretenu, idéal pour un couple ou une petite famille.',
    amenities: ['wifi', 'clim', 'tv', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Mamadou Diallo', landlordEmail: 'm.diallo@gmail.com',
  },
  {
    id: '2',
    title: 'Villa 5 Pièces avec Piscine',
    address: 'Route des Almadies',
    city: 'Almadies, Dakar',
    region: 'Dakar',
    price: 750000,
    type: 'VILLA',
    surface: 220,
    rooms: 5, beds: 4, baths: 3,
    isNew: true, isVerified: true,
    boostUntil: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Magnifique villa avec piscine privée aux Almadies. Grande terrasse, jardin tropical, garage 2 voitures. À 5 minutes de la plage.',
    amenities: ['wifi', 'clim', 'tv', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80', 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=80'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Fatou Sow', landlordEmail: 'f.sow@alloappart.sn',
  },
  {
    id: '3',
    title: 'Studio Moderne Meublé',
    address: 'Avenue Cheikh Anta Diop',
    city: 'Point E, Dakar',
    region: 'Dakar',
    price: 180000,
    type: 'STUDIO',
    surface: 42,
    rooms: 1, beds: 1, baths: 1,
    isNew: false, isVerified: true,
    boostUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Studio entièrement meublé et équipé à Point E, quartier universitaire et dynamique. Idéal pour étudiant ou jeune actif.',
    amenities: ['wifi', 'clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80'],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Ibrahima Ndiaye', landlordEmail: 'i.ndiaye@gmail.com',
  },
  {
    id: '4',
    title: 'Appartement Vue Mer',
    address: 'Corniche des Mamelles',
    city: 'Mamelles, Dakar',
    region: 'Dakar',
    price: 480000,
    type: 'APPARTEMENT',
    surface: 110,
    rooms: 3, beds: 3, baths: 2,
    isNew: false, isVerified: true,
    boostUntil: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Superbe appartement avec vue panoramique sur l\'Atlantique depuis les Mamelles. Balcon spacieux, résidence sécurisée.',
    amenities: ['wifi', 'clim', 'tv', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Aïssatou Ba', landlordEmail: 'a.ba@gmail.com',
  },
  {
    id: '5',
    title: 'Villa Résidence Sécurisée',
    address: 'Cité Sacré-Cœur 3',
    city: 'Sacré-Cœur, Dakar',
    region: 'Dakar',
    price: 620000,
    type: 'VILLA',
    surface: 180,
    rooms: 4, beds: 4, baths: 2,
    isNew: true, isVerified: false,
    description: 'Belle villa dans une résidence sécurisée de Sacré-Cœur 3. Quartier calme, cour privée, parking, générateur.',
    amenities: ['clim', 'tv', 'cuisine', 'gardien'],
    images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=80'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Oumar Diop', landlordEmail: 'o.diop@gmail.com',
  },
  {
    id: '6',
    title: 'Chambre en Colocation',
    address: 'Rue de Mermoz',
    city: 'Mermoz, Dakar',
    region: 'Dakar',
    price: 95000,
    type: 'CHAMBRE',
    surface: 25,
    rooms: 1, beds: 1, baths: 1,
    isNew: false, isVerified: true,
    boostUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Chambre meublée dans un appartement en colocation à Mermoz. Colocataires sérieux, internet inclus.',
    amenities: ['wifi', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Khadija Fall', landlordEmail: 'k.fall@gmail.com',
  },
  {
    id: '7',
    title: 'Local Commercial Centre-Ville',
    address: 'Avenue Lamine Guèye',
    city: 'Plateau, Dakar',
    region: 'Dakar',
    price: 450000,
    type: 'LOCAL',
    surface: 120,
    rooms: 3, beds: 0, baths: 1,
    isNew: true, isVerified: true,
    description: 'Local commercial idéalement situé en plein cœur du Plateau. Grande vitrine sur rue passante, accès PMR, réserve au fond. Parfait pour boutique, agence ou showroom.',
    amenities: ['clim', 'wifi'],
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Samba Touré', landlordEmail: 's.toure@gmail.com',
  },
  {
    id: '8',
    title: 'Terrain à Bâtir — Yoff',
    address: 'Quartier Yoff Layène',
    city: 'Yoff, Dakar',
    region: 'Dakar',
    price: 1200000,
    type: 'TERRAIN',
    surface: 500,
    rooms: 0, beds: 0, baths: 0,
    isNew: true, isVerified: true,
    description: 'Beau terrain à bâtir de 500m² à Yoff, titre foncier propre. Quartier en plein développement, proche mer et aéroport AIBD. Idéal pour construction villa ou immeuble R+2.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Rokhaya Gueye', landlordEmail: 'r.gueye@gmail.com',
  },

  /* ── THIÈS ─────────────────────────────────────────────── */
  {
    id: '9',
    title: 'Villa Moderne à Thiès',
    address: 'Cité Ballabey',
    city: 'Thiès',
    region: 'Thiès',
    price: 280000,
    type: 'VILLA',
    surface: 150,
    rooms: 4, beds: 3, baths: 2,
    isNew: true, isVerified: true,
    description: 'Belle villa moderne dans la cité Ballabey à Thiès. Grande cour, garage, générateur. Quartier calme et résidentiel, proche écoles et commerces.',
    amenities: ['clim', 'cuisine', 'gardien'],
    images: ['https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=1200&q=80'],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Pape Ndoye', landlordEmail: 'p.ndoye@gmail.com',
  },
  {
    id: '10',
    title: 'Appartement F3 à Mbour',
    address: 'Résidence Saly Nord',
    city: 'Mbour',
    region: 'Thiès',
    price: 200000,
    type: 'APPARTEMENT',
    surface: 75,
    rooms: 3, beds: 2, baths: 1,
    isNew: false, isVerified: true,
    description: 'Appartement F3 dans résidence calme à Mbour. Proche plage de Saly, piscine commune, gardiennage. Idéal comme résidence principale ou secondaire.',
    amenities: ['wifi', 'clim', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80'],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Marème Diouf', landlordEmail: 'm.diouf@gmail.com',
  },
  {
    id: '11',
    title: 'Terrain Constructible — Saly',
    address: 'Zone Résidentielle Saly Portudal',
    city: 'Saly',
    region: 'Thiès',
    price: 800000,
    type: 'TERRAIN',
    surface: 350,
    rooms: 0, beds: 0, baths: 0,
    isNew: true, isVerified: true,
    description: 'Terrain en zone résidentielle à Saly, à 300m de la plage. Titre foncier, viabilisé eau et électricité. Environnement touristique haut de gamme.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Alioune Badara Cissé', landlordEmail: 'a.cisse@gmail.com',
  },

  /* ── SAINT-LOUIS ────────────────────────────────────────── */
  {
    id: '12',
    title: 'Maison Coloniale — Île de Saint-Louis',
    address: 'Rue Blanchot',
    city: 'Saint-Louis',
    region: 'Saint-Louis',
    price: 320000,
    type: 'VILLA',
    surface: 200,
    rooms: 5, beds: 4, baths: 2,
    isNew: false, isVerified: true,
    description: 'Maison coloniale restaurée sur l\'île de Saint-Louis, classée UNESCO. Charme historique, grandes pièces, terrasse sur toit avec vue sur le fleuve Sénégal.',
    amenities: ['wifi', 'clim', 'tv', 'cuisine'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80'],
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Aminata Wane', landlordEmail: 'a.wane@gmail.com',
  },
  {
    id: '13',
    title: 'Studio Étudiant — Saint-Louis',
    address: 'Quartier Sor',
    city: 'Saint-Louis',
    region: 'Saint-Louis',
    price: 75000,
    type: 'STUDIO',
    surface: 30,
    rooms: 1, beds: 1, baths: 1,
    isNew: false, isVerified: false,
    description: 'Studio économique dans le quartier Sor, proche Université Gaston Berger. Idéal étudiant, transport en commun à proximité.',
    amenities: ['wifi', 'douche'],
    images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80'],
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Cheikh Sarr', landlordEmail: 'c.sarr@gmail.com',
  },

  /* ── ZIGUINCHOR ─────────────────────────────────────────── */
  {
    id: '14',
    title: 'Villa Casamançaise avec Jardin',
    address: 'Quartier Boucotte',
    city: 'Ziguinchor',
    region: 'Ziguinchor',
    price: 150000,
    type: 'VILLA',
    surface: 160,
    rooms: 4, beds: 3, baths: 2,
    isNew: true, isVerified: true,
    description: 'Magnifique villa casamançaise avec grand jardin arborisé à Ziguinchor. Architecture traditionnelle rénovée, ambiance tropicale, calme absolu.',
    amenities: ['wifi', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Jean-Baptiste Diatta', landlordEmail: 'jb.diatta@gmail.com',
  },
  {
    id: '15',
    title: 'Local Commercial — Marché Ziguinchor',
    address: 'Avenue du Marché',
    city: 'Ziguinchor',
    region: 'Ziguinchor',
    price: 120000,
    type: 'LOCAL',
    surface: 60,
    rooms: 1, beds: 0, baths: 1,
    isNew: false, isVerified: true,
    description: 'Local commercial à fort passage proche du marché central de Ziguinchor. Idéal commerce alimentaire, quincaillerie ou boutique de prêt-à-porter.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=1200&q=80'],
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Mariama Badji', landlordEmail: 'm.badji@gmail.com',
  },

  /* ── KAOLACK ────────────────────────────────────────────── */
  {
    id: '16',
    title: 'Appartement F4 — Kaolack',
    address: 'Quartier Médina',
    city: 'Kaolack',
    region: 'Kaolack',
    price: 130000,
    type: 'APPARTEMENT',
    surface: 90,
    rooms: 4, beds: 3, baths: 1,
    isNew: false, isVerified: false,
    description: 'Grand appartement F4 dans le quartier Médina de Kaolack. Bien desservi, proche marché central et gare routière. Idéal famille nombreuse.',
    amenities: ['clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80'],
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Moustapha Niang', landlordEmail: 'm.niang@gmail.com',
  },
  {
    id: '17',
    title: 'Terrain — Zone Industrielle Kaolack',
    address: 'Zone Industrielle Nord',
    city: 'Kaolack',
    region: 'Kaolack',
    price: 500000,
    type: 'TERRAIN',
    surface: 1000,
    rooms: 0, beds: 0, baths: 0,
    isNew: true, isVerified: true,
    description: 'Grand terrain de 1 000m² en zone industrielle de Kaolack. Idéal entrepôt, usine ou dépôt. Titre foncier, accès poids lourds, clôturé.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Lamine Baldé', landlordEmail: 'l.balde@gmail.com',
  },

  /* ── DIOURBEL ───────────────────────────────────────────── */
  {
    id: '18',
    title: 'Appartement F3 — Diourbel Centre',
    address: 'Quartier Ndame',
    city: 'Diourbel',
    region: 'Diourbel',
    price: 110000,
    type: 'APPARTEMENT',
    surface: 70,
    rooms: 3, beds: 2, baths: 1,
    isNew: false, isVerified: true,
    description: 'Appartement F3 bien situé au centre-ville de Diourbel. Quartier résidentiel calme, proche marchés et transports. Idéal pour une famille.',
    amenities: ['clim', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80'],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Serigne Mbaye', landlordEmail: 's.mbaye@gmail.com',
  },
  {
    id: '19',
    title: 'Villa de Standing — Touba',
    address: 'Quartier Darou Khoudoss',
    city: 'Touba',
    region: 'Diourbel',
    price: 250000,
    type: 'VILLA',
    surface: 180,
    rooms: 5, beds: 4, baths: 2,
    isNew: true, isVerified: true,
    description: 'Spacieuse villa de standing dans le quartier Darou Khoudoss à Touba. Grande cour, salle d\'eau moderne, générateur inclus. À proximité de la Grande Mosquée.',
    amenities: ['clim', 'cuisine', 'douche', 'gardien', 'tv'],
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Modou Mbacké', landlordEmail: 'm.mbacke@gmail.com',
  },
  {
    id: '20',
    title: 'Bureau Équipé — Diourbel',
    address: 'Avenue Cheikh Ibrahima Fall',
    city: 'Diourbel',
    region: 'Diourbel',
    price: 180000,
    type: 'BUREAU',
    surface: 55,
    rooms: 3, beds: 0, baths: 1,
    isNew: false, isVerified: true,
    description: 'Bureau équipé idéalement situé à Diourbel. Salle de réunion, accueil, deux open spaces. Climatisation, fibre optique, parking sécurisé. Adapté PME ou représentation régionale.',
    amenities: ['wifi', 'clim'],
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80'],
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Ndèye Astou Dieng', landlordEmail: 'n.dieng@gmail.com',
  },

  /* ── LOUGA ──────────────────────────────────────────────── */
  {
    id: '21',
    title: 'Appartement Moderne — Louga',
    address: 'Cité Léona',
    city: 'Louga',
    region: 'Louga',
    price: 95000,
    type: 'APPARTEMENT',
    surface: 65,
    rooms: 3, beds: 2, baths: 1,
    isNew: true, isVerified: false,
    description: 'Appartement moderne dans la cité Léona à Louga. Bien desservi, proche gare et commerces. Idéal pour famille ou actif en déplacement.',
    amenities: ['clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80'],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Thierno Diallo', landlordEmail: 't.diallo@gmail.com',
  },
  {
    id: '22',
    title: 'Terrain à Bâtir — Linguère',
    address: 'Zone d\'extension Nord',
    city: 'Linguère',
    region: 'Louga',
    price: 180000,
    type: 'TERRAIN',
    surface: 400,
    rooms: 0, beds: 0, baths: 0,
    isNew: false, isVerified: true,
    description: 'Terrain à bâtir de 400m² à Linguère, titré et viabilisé. Zone en plein développement, accès route nationale. Idéal construction villa ou commerce.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80'],
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Abdou Sy', landlordEmail: 'a.sy@gmail.com',
  },

  /* ── FATICK ─────────────────────────────────────────────── */
  {
    id: '23',
    title: 'Villa Traditionnelle — Fatick',
    address: 'Quartier Fayil',
    city: 'Fatick',
    region: 'Fatick',
    price: 130000,
    type: 'VILLA',
    surface: 140,
    rooms: 4, beds: 3, baths: 1,
    isNew: false, isVerified: true,
    description: 'Belle villa traditionnelle à Fatick avec grande cour intérieure. Quartier résidentiel paisible, proche du fleuve Sine. Jardin fruitier, puits.',
    amenities: ['cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80'],
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Babacar Faye', landlordEmail: 'b.faye@gmail.com',
  },
  {
    id: '24',
    title: 'Studio Meublé — Foundiougne',
    address: 'Bord de Fleuve',
    city: 'Foundiougne',
    region: 'Fatick',
    price: 60000,
    type: 'STUDIO',
    surface: 28,
    rooms: 1, beds: 1, baths: 1,
    isNew: true, isVerified: false,
    description: 'Studio meublé avec vue sur le fleuve Saloum à Foundiougne. Idéal pour travailleur ou expatrié. Ambiance mangrove, calme total, piroguier à 50m.',
    amenities: ['wifi', 'douche'],
    images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Ndéye Sène', landlordEmail: 'n.sene@gmail.com',
  },

  /* ── KOLDA ──────────────────────────────────────────────── */
  {
    id: '25',
    title: 'Appartement F4 — Kolda',
    address: 'Quartier Saré Guilel',
    city: 'Kolda',
    region: 'Kolda',
    price: 90000,
    type: 'APPARTEMENT',
    surface: 80,
    rooms: 4, beds: 3, baths: 1,
    isNew: false, isVerified: false,
    description: 'Grand appartement familial dans le quartier Saré Guilel à Kolda. Proche des institutions administratives, marché et lycées. Bon rapport qualité-prix.',
    amenities: ['clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80'],
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Ousmane Baldé', landlordEmail: 'o.balde@gmail.com',
  },
  {
    id: '26',
    title: 'Local Commercial — Vélingara',
    address: 'Avenue du Commerce',
    city: 'Vélingara',
    region: 'Kolda',
    price: 70000,
    type: 'LOCAL',
    surface: 45,
    rooms: 1, beds: 0, baths: 1,
    isNew: true, isVerified: true,
    description: 'Local commercial à forte visibilité sur l\'axe principal de Vélingara. Idéal épicerie, pharmacie ou boutique de téléphonie. Bail flexible.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80'],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Fatoumata Diallo', landlordEmail: 'f.diallo@gmail.com',
  },

  /* ── TAMBACOUNDA ────────────────────────────────────────── */
  {
    id: '27',
    title: 'Villa avec Jardin — Tambacounda',
    address: 'Cité Résidentielle SICAP',
    city: 'Tambacounda',
    region: 'Tambacounda',
    price: 160000,
    type: 'VILLA',
    surface: 160,
    rooms: 4, beds: 3, baths: 2,
    isNew: false, isVerified: true,
    description: 'Villa bien entretenue dans la cité SICAP de Tambacounda. Grand jardin ombragé, garage, groupe électrogène. Idéal pour cadre expatrié ou fonctionnaire.',
    amenities: ['clim', 'cuisine', 'douche', 'gardien', 'tv'],
    images: ['https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=1200&q=80'],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Boubacar Dramé', landlordEmail: 'b.drame@gmail.com',
  },
  {
    id: '28',
    title: 'Bureau Administratif — Tambacounda',
    address: 'Avenue Léopold Sédar Senghor',
    city: 'Tambacounda',
    region: 'Tambacounda',
    price: 150000,
    type: 'BUREAU',
    surface: 70,
    rooms: 4, beds: 0, baths: 1,
    isNew: true, isVerified: false,
    description: 'Bureau administratif de 70m² en plein centre de Tambacounda. Salle de réunion, hall d\'accueil, deux bureaux indépendants. Climatisation centralisée.',
    amenities: ['wifi', 'clim'],
    images: ['https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80'],
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Adja Kouyaté', landlordEmail: 'a.kouyate@gmail.com',
  },

  /* ── MATAM ──────────────────────────────────────────────── */
  {
    id: '29',
    title: 'Appartement F3 — Matam',
    address: 'Quartier Sinthiou Balel',
    city: 'Matam',
    region: 'Matam',
    price: 80000,
    type: 'APPARTEMENT',
    surface: 60,
    rooms: 3, beds: 2, baths: 1,
    isNew: false, isVerified: false,
    description: 'Appartement F3 à Matam, ville en plein développement grâce aux investissements de la diaspora. Proche fleuve Sénégal, quartier tranquille.',
    amenities: ['clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80'],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Hamidou Bâ', landlordEmail: 'h.ba@gmail.com',
  },
  {
    id: '30',
    title: 'Chambre Meublée — Kanel',
    address: 'Centre de Kanel',
    city: 'Kanel',
    region: 'Matam',
    price: 35000,
    type: 'CHAMBRE',
    surface: 20,
    rooms: 1, beds: 1, baths: 1,
    isNew: false, isVerified: false,
    description: 'Chambre meublée dans une maison familiale à Kanel. Idéal pour fonctionnaire ou enseignant en affectation. Repas possible sur demande.',
    amenities: ['douche', 'cuisine'],
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80'],
    createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Mariama Balde', landlordEmail: 'm.balde@gmail.com',
  },

  /* ── KAFFRINE ───────────────────────────────────────────── */
  {
    id: '31',
    title: 'Appartement Familial — Kaffrine',
    address: 'Quartier Ndoulo',
    city: 'Kaffrine',
    region: 'Kaffrine',
    price: 100000,
    type: 'APPARTEMENT',
    surface: 75,
    rooms: 3, beds: 2, baths: 1,
    isNew: true, isVerified: true,
    description: 'Appartement spacieux dans un quartier résidentiel de Kaffrine. Carrelé, plafond haut, belle luminosité. Proche préfecture et hôpital régional.',
    amenities: ['clim', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Ibou Ndoye', landlordEmail: 'i.ndoye@gmail.com',
  },
  {
    id: '32',
    title: 'Terrain Agricole — Birkelane',
    address: 'Route de Kaolack',
    city: 'Birkelane',
    region: 'Kaffrine',
    price: 120000,
    type: 'TERRAIN',
    surface: 2000,
    rooms: 0, beds: 0, baths: 0,
    isNew: false, isVerified: false,
    description: 'Grand terrain agricole de 2 hectares à Birkelane. Sol fertile, accès eau, clôturé partiellement. Idéal maraîchage, élevage ou projet agro-industriel.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80'],
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Adama Diop', landlordEmail: 'a.diop@gmail.com',
  },

  /* ── SÉDHIOU ────────────────────────────────────────────── */
  {
    id: '33',
    title: 'Villa Casamançaise — Sédhiou',
    address: 'Quartier Bambali',
    city: 'Sédhiou',
    region: 'Sédhiou',
    price: 115000,
    type: 'VILLA',
    surface: 145,
    rooms: 4, beds: 3, baths: 1,
    isNew: false, isVerified: true,
    description: 'Villa de style casamançais dans le quartier Bambali à Sédhiou. Jardin arborisé, bord du Casamance, ambiance verdoyante. Idéal pour famille ou retraite.',
    amenities: ['cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80'],
    createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Djibril Sambou', landlordEmail: 'd.sambou@gmail.com',
  },
  {
    id: '34',
    title: 'Studio Fonctionnel — Bounkiling',
    address: 'Centre-ville Bounkiling',
    city: 'Bounkiling',
    region: 'Sédhiou',
    price: 50000,
    type: 'STUDIO',
    surface: 25,
    rooms: 1, beds: 1, baths: 1,
    isNew: true, isVerified: false,
    description: 'Petit studio fonctionnel à Bounkiling. Idéal enseignant, infirmier ou fonctionnaire affecté en région. Quartier central, transport facile.',
    amenities: ['douche'],
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Marie-Paule Manga', landlordEmail: 'm.manga@gmail.com',
  },

  /* ── KÉDOUGOU ───────────────────────────────────────────── */
  {
    id: '35',
    title: 'Appartement — Kédougou',
    address: 'Quartier Salemata',
    city: 'Kédougou',
    region: 'Kédougou',
    price: 90000,
    type: 'APPARTEMENT',
    surface: 65,
    rooms: 3, beds: 2, baths: 1,
    isNew: false, isVerified: false,
    description: 'Appartement dans un quartier résidentiel de Kédougou. Ville carrefour de l\'or et de l\'écotourisme, en plein essor. Proche de tous les services publics.',
    amenities: ['clim', 'cuisine', 'douche'],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80'],
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Mamadou Camara', landlordEmail: 'm.camara@gmail.com',
  },
  {
    id: '36',
    title: 'Terrain — Zone Minière Saraya',
    address: 'Route de Saraya',
    city: 'Saraya',
    region: 'Kédougou',
    price: 200000,
    type: 'TERRAIN',
    surface: 800,
    rooms: 0, beds: 0, baths: 0,
    isNew: true, isVerified: true,
    description: 'Terrain de 800m² près de la zone minière de Saraya. Accès piste carrossable, titre foncier disponible. Potentiel commercial et industriel fort.',
    amenities: [],
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Daouda Konaté', landlordEmail: 'd.konate@gmail.com',
  },

  /* ── DAKAR (suite) ─ BUREAU + Rufisque ─────────────────── */
  {
    id: '37',
    title: 'Plateau Business Center — Bureau Clé en Main',
    address: 'Rue Carnot',
    city: 'Plateau, Dakar',
    region: 'Dakar',
    price: 650000,
    type: 'BUREAU',
    surface: 95,
    rooms: 5, beds: 0, baths: 2,
    isNew: true, isVerified: true,
    description: 'Bureau clé en main au Plateau, cœur des affaires de Dakar. Open space + 2 bureaux fermés + salle de réunion + kitchenette. Fibre dédiée, climatisation réversible, accueil partagé.',
    amenities: ['wifi', 'clim', 'tv'],
    images: ['https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80', 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Seydou Niane', landlordEmail: 's.niane@alloappart.sn',
  },
  {
    id: '38',
    title: 'Appartement F3 — Rufisque',
    address: 'Cité Jaxaay',
    city: 'Rufisque',
    region: 'Dakar',
    price: 160000,
    type: 'APPARTEMENT',
    surface: 72,
    rooms: 3, beds: 2, baths: 1,
    isNew: false, isVerified: true,
    description: 'Appartement F3 dans la cité Jaxaay à Rufisque. Proche du centre-ville, marchés et écoles. Bon accès via autoroute à péage. Idéal pour famille travaillant à Dakar.',
    amenities: ['clim', 'cuisine', 'douche', 'gardien'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80'],
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    landlordName: 'Astou Ndiaye', landlordEmail: 'a.ndiaye@gmail.com',
  },
];

export function getMockListing(id: string): MockListing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id);
}
